trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Terraform

stages:  
- stage: Init_TF  
  jobs:  
  - job: Init_TF
    steps:
    - task: terraformInstaller@0
      inputs:
      terraformVersion: '0.12.12'
      displayName: Install Terraform
    

